package com.pnm.habitsync.data.model

// Represents a single Habit
data class Habit(
    val id: String = "",           // Unique ID generated by Firebase
    val userId: String = "",
    val title: String = "",
    val category: String = "",
    val description: String = "",
    val streakCount: Int = 0,
    val lastCompletedDate: String = "",
    val public: Boolean = false,
    val createdAt: Long = System.currentTimeMillis()
)